service: !u FP.Service.ConfigDB
version: 1
classes:
  - !u E.Class.Cluster
  # XXX Needed for now
  - !u FP.Class.Service
  - !u FP.Class.PermGroup
  - !u FP.Class.Permission
  - !u FP.Class.Requirement
objects:
  !u FP.Class.App:
    - !u E.App.Cluster
    - !u E.App.Status
    - !u E.App.HelmChart
    - !u E.App.HelmRelease
    # XXX Needed for now
    - !u FP.App.ConfigSchema
  !u FP.Class.Service:
    - !u E.Service.EdgeDeployment
  !u FP.Class.PermGroup:
    - !u E.Perm.All
  !u FP.Class.Permission:
    - !u E.Perm.Clusters
    - !u E.Perm.Secrets
  !u FP.Class.Requirement:
    - !u E.Requirement.ServiceAccount
    - !u E.Requirement.EdgeRepos
    - !u E.Requirement.Groups
    - !u E.Requirement.FluxAccounts
    - !u E.Requirement.FluxRoles
configs:
  !u FP.App.Info:
    !u E.Class.Cluster: { name: "Edge cluster" }
    !u E.App.Cluster: { name: "Edge cluster configuration" }
    !u E.App.Status: { name: "Edge cluster setup status" }
    !u E.App.HelmChart: { name: "Helm chart template" }
    !u E.App.HelmRelease: { name: "HelmRelease template" }
    !u E.Service.EdgeDeployment: { name: "Edge Deployment Operator" }
    !u E.Perm.All: { name: "Edge Deployment permissions" }
    !u E.Perm.Clusters: { name: "Edge: Manage clusters" }
    !u E.Perm.Secrets: { name: "Edge: Manage secrets" }
    !u E.Requirement.ServiceAccount: { name: "Edge Deployment service account" }
    !u E.Requirement.EdgeRepos: { name: "Edge cluster repositories" }
    !u E.Requirement.Groups: { name: "EDO-managed groups" }
    !u E.Requirement.FluxAccounts: { name: "Edge flux accounts" }
    !u E.Requirement.FluxRoles: { name: "Edge flux roles" }
  !u FP.App.ConfigSchema:
    !u E.App.Cluster:
      title: Edge cluster configuration
      type: object
      required: [name, namespace]
      additionalProperties: false
      properties:
        name:
          description: A name for the cluster.
          type: string
        namespace:
          description: The k8s namespace to deploy to.
          type: string
        chart:
          description: The Helm chart to deploy.
          type: string
          format: uuid
    !u E.App.Status:
      title: EDO private status
      type: object
      additionalProperties: true
      # No additional constraints, this is our private data
