apiVersion: batch/v1
kind: Job
metadata:
  name: post-delete-cleanup
  annotations:
    "helm.sh/hook": post-delete
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      serviceAccountName: post-delete-cleanup
      containers:
        - name: script-runner
{{ include "amrc-connectivity-stack.image" (list . .Values.kubectl) | indent 10 }}
          command:
            - /bin/sh
            - -c
            - |
              echo "Starting cleanup..."
              for i in $(kubectl -n {{ .Release.Namespace }} get kerberos-keys -o name); do kubectl -n {{ .Release.Namespace }} patch $i --type=json -p='[{"op": "remove", "path": "/metadata/finalizers"}]'; done
              echo "Cleanup complete!"
      restartPolicy: Never
  backoffLimit: 3

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-delete-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete,post-delete
    "helm.sh/hook-delete-policy": before-hook-creation

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: post-delete-cleanup-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete,post-delete
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [ "factoryplus.app.amrc.co.uk" ]
    resources: [ "kerberos-keys" ]
    verbs: [ "get", "list", "patch" ] # Specify only necessary actions

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: post-delete-cleanup-binding
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete,post-delete
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
  - kind: ServiceAccount
    name: post-delete-cleanup
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: post-delete-cleanup-role
  apiGroup: rbac.authorization.k8s.io
