{{- $k8sname := include "opcua-server.k8sname" .Values.name }}
{{- $secretName := printf "opcua-server-opcua-creds.%s" $k8sname }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $secretName }}
  labels:
    factory-plus.app: opcua-server
    factory-plus.uuid: {{ .Values.uuid }}
type: Opaque
stringData:
  username: {{ .Values.opcua.username | quote }}
---
apiVersion: factoryplus.app.amrc.co.uk/v1
kind: LocalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $secretName }}
  labels:
    factory-plus.app: opcua-server
    factory-plus.uuid: {{ .Values.uuid }}
spec:
  format: Password
  secret: {{ $secretName }}
  key: password
