{{- $k8sname := include "opcua-server.k8sname" .Values.name }}
{{- $secretName := printf "opcua-server-opcua-creds.%s" $k8sname }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $secretName }}
  labels:
    factory-plus.app: opcua-server
    factory-plus.uuid: {{ .Values.uuid }}
type: Opaque
data:
{{- if $existingSecret }}
  username: {{ index $existingSecret.data "username" }}
  password: {{ index $existingSecret.data "password" }}
{{- else }}
  username: {{ .Values.opcua.username | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
